image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
environment:
  site: radio.theparanoidtimes.org
tasks:
  - package: |
      cd radio-log/src
      tar -cvz . > ../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
